### ISSUE TITLE
Acrobat 64-Bit

### ISSUE THREAD

**Issue by medimetriks** [DanysysTeam/PS-SFTA#14]
This worked great for making the 32-bit version of Acrobat Reader the default for PDFs but Acrobat Reader updated to the 64-Bit and this no longer works.

Any ideas how to make the 64-bit version the default?

**Comment by medimetriks** [comment]
I am not sure how to tell.  I had the 32-bit version installed, it automatically updated to the 64-bit version.  I then manually changed the default reader to be MS Edge as a test, then when I try to use the powershell -ExecutionPolicy Bypass -command "& { . C:\install\SFTA.ps1; Set-FTA 'AcroExch.Document.DC' '.pdf' }" command it does not change the default reader.

**Comment by Danyfirex** [comment]
I suppose it probably changed the program Id.  I'm traveling, anyway I'll check next week and try to find a solution.

**Comment by medimetriks** [comment]
Thanks

**Comment by medimetriks** [comment]
> I suppose it probably changed the program Id. I'm traveling, anyway I'll check next week and try to find a solution.



> I suppose it probably changed the program Id. I'm traveling, anyway I'll check next week and try to find a solution.



> I suppose it probably changed the program Id. I'm traveling, anyway I'll check next week and try to find a solution.

Thanks

**Comment by Danyfirex** [comment]
Hello @medimetriks  I get it working with this ProgramId **Acrobat.Document.DC**

I run it like this:
`powershell -ExecutionPolicy Bypass -command "& { . .\SFTA.ps1; Set-FTA 'Acrobat.Document.DC' '.pdf' }"`

let me know if it works. Sorry for delay I just arrived a couple of hours ago.

**Comment by medimetriks** [comment]
I'm away for the weekend,  I'll try it on Monday.

Thanks,
Alan

Alan Koop
Director - Technology
Medimetriks Pharmaceuticals, Inc.

383 Route 46 West
Fairfield, NJ 07004
Office- 973-882-7512, ext. 553
Fax-973-882-7502
Mobile-973-553-0427
www.medimetriks.com

NOTICE:  The content of this e-mail message and any attachments is 
confidential, may be legally privileged and is intended solely for the use 
of the intended recipient.  If you are not the intended recipient, be 
advised that any use, dissemination, distribution or copying of this e-mail 
and any attachment is strictly prohibited.  If you are not the intended 
recipient, you should not review, retransmit, convert to hard copy, copy, 
use or disseminate this e-mail or any attachment.  If you have received 
this e-mail in error, please immediately notify us by return e-mail and 
delete this message and any attachment from your computer system.  Thank you

**Comment by Danyfirex** [comment]
Could you run using -Verbose to check if It's failing? and paste console output here,

**Comment by medimetriks** [comment]
Is the –Verbose part of the Powershell command?  When I try to add it I get the following:

 

C:\Users\MediRep>powershell -ExecutionPolicy Bypass -Verbose -command ""&" {. c:\install\SFTA.ps1; Set-FTA 'Acrobat.Document.DC' '.pdf'}"

-Verbose : The term '-Verbose' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was

included, verify that the path is correct and try again.

At line:1 char:1

+ -Verbose -command

+ ~~~~~~~~

    + CategoryInfo          : ObjectNotFound: (-Verbose:String) [], CommandNotFoundException

    + FullyQualifiedErrorId : CommandNotFoundException

 

 

Alan Koop 
Director - Technology 
Medimetriks Pharmaceuticals, Inc. 
383 Route 46 West 
Fairfield, NJ 07004 

Office- 973-882-7512, ext. 553 
Fax-973-882-7502 
Mobile-973-553-0427

www.medimetriks.com <http://www.medimetriks.com/> 

NOTICE:  The content of this e-mail message and any attachments is confidential, may be legally privileged and is intended solely for the use of the intended recipient.  If you are not the intended recipient, be advised that any use, dissemination, distribution or copying of this e-mail and any attachment is strictly prohibited.  If you are not the intended recipient, you should not review, retransmit, convert to hard copy, copy, use or disseminate this e-mail or any attachment.  If you have received this e-mail in error, please immediately notify us by return e-mail and delete this message and any attachment from your computer system.  Thank you.

**Comment by Danyfirex** [comment]
this: 
`powershell -ExecutionPolicy Bypass -Verbose -command ""&" {. c:\install\SFTA.ps1; Set-FTA 'Acrobat.Document.DC' '.pdf' -Verbose}"`

**Comment by medimetriks** [comment]
It doesn’t like the –Verbose.  See below.

 

C:\Users\MediRep>powershell -ExecutionPolicy Bypass -Verbose -command ""&" {. c:\install\SFTA.ps1; Set-FTA 'Acrobat.Document.DC' '.pdf' -Verbose}"

-Verbose : The term '-Verbose' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was

included, verify that the path is correct and try again.

At line:1 char:1

+ -Verbose -command

+ ~~~~~~~~

    + CategoryInfo          : ObjectNotFound: (-Verbose:String) [], CommandNotFoundException

    + FullyQualifiedErrorId : CommandNotFoundException

 

 

Alan Koop 
Director - Technology 
Medimetriks Pharmaceuticals, Inc. 
383 Route 46 West 
Fairfield, NJ 07004 

Office- 973-882-7512, ext. 553 
Fax-973-882-7502 
Mobile-973-553-0427

www.medimetriks.com <http://www.medimetriks.com/> 

NOTICE:  The content of this e-mail message and any attachments is confidential, may be legally privileged and is intended solely for the use of the intended recipient.  If you are not the intended recipient, be advised that any use, dissemination, distribution or copying of this e-mail and any attachment is strictly prohibited.  If you are not the intended recipient, you should not review, retransmit, convert to hard copy, copy, use or disseminate this e-mail or any attachment.  If you have received this e-mail in error, please immediately notify us by return e-mail and delete this message and any attachment from your computer system.  Thank you.

**Comment by Danyfirex** [comment]
This like this:

`powershell -ExecutionPolicy Bypass -command "& { . 'c:\install\SFTA.ps1'; Set-FTA 'Acrobat.Document.DC' '.pdf' -Verbose }"
`

**Comment by medimetriks** [comment]
That worked!  It looks like Acrobat is now the default viewer too!!!

 

Here is the output:

 

C:\Users\MediRep>powershell -ExecutionPolicy Bypass -command "& { . 'c:\install\SFTA.ps1'; Set-FTA 'Acrobat.Document.DC' '.pdf' -Verbose }"

VERBOSE: ProgId: Acrobat.Document.DC

VERBOSE: Extension/Protocol: .pdf

VERBOSE: Getting Hash For Acrobat.Document.DC   .pdf

VERBOSE: Use Get-UserSid

VERBOSE: baseInfo: .pdfs-1-5-21-1707439469-2689279175-4168427093-1002acrobat.document.dc01d8a0f91ceca000user choice set via windows user experience

{d18b6dd5-6124-4341-9318-804003bafa0b}

VERBOSE: Hash: lc1ytN3zRIc=

VERBOSE: Write Reg ApplicationAssociationToasts OK: Acrobat.Document.DC_.pdf

VERBOSE: Write Reg ApplicationAssociationToastsList OK: Applications\Acrobat.exe_.pdf

VERBOSE: Write Reg ApplicationAssociationToastsList OK: Applications\AcroRd32.exe_.pdf

VERBOSE: Write Reg ApplicationAssociationToastsList OK: Applications\winword.exe_.pdf

VERBOSE: Write Reg ApplicationAssociationToastsList OK: MSEdgePDF_.pdf

VERBOSE: Write Reg ApplicationAssociationToastsList OK: Acrobat.Document.DC_.pdf

VERBOSE: Write Reg ApplicationAssociationToastsList OK: (default)_.pdf

VERBOSE: Write Reg ApplicationAssociationToastsList OK: MSEdgePDF_.pdf

VERBOSE: Write Registry Extension: .pdf

VERBOSE: Remove Extension UserChoice Key If Exist: Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.pdf\UserChoice

VERBOSE: Write Reg Extension UserChoice OK

 

Alan Koop 
Director - Technology 
Medimetriks Pharmaceuticals, Inc. 
383 Route 46 West 
Fairfield, NJ 07004 

Office- 973-882-7512, ext. 553 
Fax-973-882-7502 
Mobile-973-553-0427

www.medimetriks.com <http://www.medimetriks.com/> 

NOTICE:  The content of this e-mail message and any attachments is confidential, may be legally privileged and is intended solely for the use of the intended recipient.  If you are not the intended recipient, be advised that any use, dissemination, distribution or copying of this e-mail and any attachment is strictly prohibited.  If you are not the intended recipient, you should not review, retransmit, convert to hard copy, copy, use or disseminate this e-mail or any attachment.  If you have received this e-mail in error, please immediately notify us by return e-mail and delete this message and any attachment from your computer system.  Thank you.
