### ISSUE TITLE
When there is a space in the path to exe, `Register-FTA` doesn't work

### ISSUE THREAD

**Issue by SerVB** [DanysysTeam/PS-SFTA#20]
There is an error logged that `Test-Path $_` fails when I call `Register-FTA` with a path with spaces, like `Register-FTA "C:\my path\app.exe" .abc`.

Anyway, thank you for the repo!

**Comment by Danyfirex** [comment]
I don't get that issue. I'm using like this:
`powershell -ExecutionPolicy Bypass -command "& { . .\SFTA.ps1; Register-FTA 'C:\Folder Space\Msgbox.exe' '.abc' }"`

I also do it like this:
`. .\SFTA.ps1`

then:
`Register-FTA "C:\Folder Space\Msgbox.exe" .abc -verbose`

and all fine. Show me a runnable code to reproduce the issue.

**Comment by SerVB** [comment]
Thanks! I rechecked and it works for me now. I don't know why it didn't work two weeks ago for me because I did the same actions. Sorry for bothering. Closing.
