### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by noelhibbard** [DanysysTeam/PS-SFTA#21]
Sorry to clutter the issues with a non-issue but wanted to say thanks for putting this together. I was making headway using procmon to monitor the registry but the stupid hashing algorithm would have taken forever to figure out. Every time I have the need to programmatically set a file extension in windows its like starting all over again. Surely Microsoft could find a way to prevent hijacking without making it impossible to do programmatically in a non-hacky way.

Anyways, thanks!

**Comment by eabase** [comment]
I came from a link in the SO question:
* https://stackoverflow.com/questions/73122968/how-to-change-the-file-association-for-excel-urls-using-excel-urilink-16

So this repo is very useful. Thank you.
