### ISSUE TITLE
Change registry values for different user

### ISSUE THREAD

**Issue by flox44** [DanysysTeam/PS-SFTA#22]
Hi,

Is it possible to change the registry entries for a different user than the script was started from? 

If I change the registry values in the script with them from the specific user SID, it doesn't work.

I hope I post this in the right category here.

Thanks

**Comment by Danyfirex** [comment]
I've never done before. have you tried using Start-Process powershell.exe adding -Credential $Credential? I think it may work.

**Comment by flox44** [comment]
That could do it but won’t be a solution for me. Because I have to fully automate the installation without any UI, and if you do it with $Credential, powershell asks for password (We‘re in a Windows Domain, so the password can’t be stored for every user - I think?!)
