### ISSUE TITLE
Commands Aren't Recognized

### ISSUE THREAD

**Issue by RainzDev** [DanysysTeam/PS-SFTA#29]
When I try to run the script and then running any of the commands, it doesn't recognize any of them. I've ran into errors before, but that was just about the policy thing which I bypassed using a powershell command.

**Comment by Danyfirex** [comment]
and?  I don't' understand your issue.

**Comment by RainzDev** [comment]
> and?  I don't' understand your issue. 

The main issue is that none of the commands are being recognizable for powershell. For example, i tried using Set-PTA

"'Set-PTA' is not recognized as the name of a cmdlet, function, script file, or operable program."

**Comment by Danyfirex** [comment]
how are you running the script?

**Comment by RainzDev** [comment]
> how are you running the script?

`.\SFTA.ps1`

**Comment by Danyfirex** [comment]
check your Powershell Execution Policy

**Comment by RainzDev** [comment]
> check your Powershell Execution Policy

It's set as bypass.

**Comment by Danyfirex** [comment]
have you used the command adding -verbose parameter?

**Comment by RainzDev** [comment]
Nope, is that needed?

**Comment by RainzDev** [comment]
If yes, then I tried it just now and it still doesn't work when I try to run the script again.

**Comment by Danyfirex** [comment]
not needed I'm just trying to determine your issue. what error do you see when trying to run a command?

**Comment by RainzDev** [comment]
No errors. Don't worry though, I managed to get it to run by doing `Import-Module .\SFTA.ps1` instead
