### ISSUE TITLE
Question ?

### ISSUE THREAD

**Issue by mikhoul** [DanysysTeam/PS-SFTA#3]
First thanks for this scripts ! :+1: 

Could you explain to me what is the difference between Set-FTA and  Register-FTA ?  🤔

Could I always use Regsiter-FTA with the path of the program instead of using Set-FTA with the program ID since are hard to find when program are not associated already with an extension ? 

It's not clear to me the difference between the two, some simple exemples when to use them would help me a lot.

One last question: With Set-PTA could I use a path instead of a program-ID ?

Best Regards ! :octocat:

**Comment by Danyfirex** [comment]
Hello @mikhoul  
The difference is that Set-FTA is used for already installed applications and Register-FTA is for a portable application. 

I would prefer to use Register-FTA only with Portable applications.

About Set-PTA It will not register the application first. So You would need to use Register-FTA. Set-PTA is just a wrapper function, internally it use Set-FTA so You could use Register-FTA passing a protocol instead a file type. it will work. Just do this way.

```powershell
Register-FTA "C:\DemoApp.exe" ftp
```
Regards

**Comment by mikhoul** [comment]
> Register-FTA passing a protocol instead a file type. it will work. Just do this way.

I figured it last night, I was successful in associating the FTP protocol to Brave using  Register-FTA.
