### ISSUE TITLE
Change between Windows Release 1909 and 2009

### ISSUE THREAD

**Issue by ReneNyffenegger** [DanysysTeam/PS-SFTA#6]
Do you happen to know if something has changed in Windows between Release 1909 (Build 18363) and 2009 (Build 19042)? The script changes an association perfectly on 1909, but doesn't succeed in 2009 (yet without error message).

**Comment by Danyfirex** [comment]
I've tested over Windows 10 20H2 19042 and all was fine. Could you give more information. how you using the script and association you're trying to setup.

**Comment by ReneNyffenegger** [comment]
It turns out that on the 2009 machine, I had a default value under the registry key `hkcu:\Software\classes\.sql` (`.sql` being the extension I wanted to associate with a program). When I removed this default value, evertyhing was fine.
